services:
  - type: web
    name: frontend-link-in-bio
    env: node
    buildCommand: npm run build
    startCommand: npm start
    plan: free
    region: oregon
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        sync: false